language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "stable"
cache:
  directories:
  - node_modules

install:
  - npm install

before_deploy:
  - npm install
  - npm run build
  - rm -rf node_modules/

jobs:
  include:
    - stage: deploy
      if: branch = master
      name: "Deploy to gh-pages"
      script: skip
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep-history: true
        local_dir: public
        on:
           branch: master

