language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "12"
deploy:
  provider: script
  script: npm install && npm run deploy
  skip_cleanup: true
  with:
    COSMIC_READ_KEY: ${{ secrets.COSMIC_READ_KEY }}
    COSMIC_BUCKET_SLUG: ${{ secrets.COSMIC_BUCKET_SLUG }}
  on:
    branch: master
